# permissions for end users to view neutronapis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: neutronapi-viewer-role
rules:
- apiGroups:
  - neutron.openstack.org
  resources:
  - neutronapis
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - neutron.openstack.org
  resources:
  - neutronapis/status
  verbs:
  - get
