kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: neutron-operator
  namespace: openstack
rules:
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - get
  - create
  - watch
  - patch
  - update
  - delete
