apiVersion: v1
kind: SecurityContextConstraints
metadata:
  name: neutron
allowPrivilegedContainer: true
allowPrivilegeEscalation: true
allowHostDirVolumePlugin: true
priority:
allowHostIPC: true
allowHostNetwork: true
allowHostPID: true
allowHostPorts: false
allowedCapabilities:
  - '*'
defaultAddCapabilities: []
readOnlyRootFilesystem: false
requiredDropCapabilities: []
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
seccompProfiles:
  - '*'
supplementalGroups:
  type: RunAsAny
users:
  - system:serviceaccount:openstack:neutron
groups: []
volumes:
  - '*'
