apiVersion: neutron.openstack.org/v1beta1
kind: NeutronAPI
metadata:
  name: neutron
  namespace: openstack
spec:
  serviceUser: neutron
  customServiceConfig: |
    [DEFAULT]
    debug = true
  databaseInstance: openstack
  databaseUser: neutron
  debug:
    dbSync: false
    service: false
  preserveJobs: false
  containerImage: quay.io/tripleozedcentos9/openstack-neutron-server:current-tripleo
  replicas: 1
  secret: neutron-secret
